// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.laby.client.managed.request;

import com.google.gwt.requestfactory.shared.EntityProxy;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

public abstract class ApplicationEntityTypesProcessor<T> {

    private final T defaultValue;

    private T result;

    public ApplicationEntityTypesProcessor() {
        defaultValue = null;
    }

    public ApplicationEntityTypesProcessor(T defaultValue) {
        this.defaultValue = defaultValue;
    }

    public static Set<java.lang.Class<? extends com.google.gwt.requestfactory.shared.EntityProxy>> getAll() {
        Set<Class<? extends EntityProxy>> rtn = new HashSet<Class<? extends EntityProxy>>();
        rtn.add(ScoreProxy.class);
        rtn.add(NiveauProxy.class);
        rtn.add(MechantProxy.class);
        rtn.add(JoueurProxy.class);
        rtn.add(CaseElementProxy.class);
        rtn.add(BonusProxy.class);
        return Collections.unmodifiableSet(rtn);
    }

    private static void process(org.laby.client.managed.request.ApplicationEntityTypesProcessor<?> processor, Class<?> clazz) {
        if (ScoreProxy.class.equals(clazz)) {
            processor.handleScore((ScoreProxy) null);
            return;
        }
        if (NiveauProxy.class.equals(clazz)) {
            processor.handleNiveau((NiveauProxy) null);
            return;
        }
        if (MechantProxy.class.equals(clazz)) {
            processor.handleMechant((MechantProxy) null);
            return;
        }
        if (JoueurProxy.class.equals(clazz)) {
            processor.handleJoueur((JoueurProxy) null);
            return;
        }
        if (CaseElementProxy.class.equals(clazz)) {
            processor.handleCaseElement((CaseElementProxy) null);
            return;
        }
        if (BonusProxy.class.equals(clazz)) {
            processor.handleBonus((BonusProxy) null);
            return;
        }
        processor.handleNonProxy(null);
    }

    private static void process(org.laby.client.managed.request.ApplicationEntityTypesProcessor<?> processor, Object proxy) {
        if (proxy instanceof ScoreProxy) {
            processor.handleScore((ScoreProxy) proxy);
            return;
        }
        if (proxy instanceof NiveauProxy) {
            processor.handleNiveau((NiveauProxy) proxy);
            return;
        }
        if (proxy instanceof MechantProxy) {
            processor.handleMechant((MechantProxy) proxy);
            return;
        }
        if (proxy instanceof JoueurProxy) {
            processor.handleJoueur((JoueurProxy) proxy);
            return;
        }
        if (proxy instanceof CaseElementProxy) {
            processor.handleCaseElement((CaseElementProxy) proxy);
            return;
        }
        if (proxy instanceof BonusProxy) {
            processor.handleBonus((BonusProxy) proxy);
            return;
        }
        processor.handleNonProxy(proxy);
    }

    public void handleNonProxy(Object object) {
    }

    public abstract void handleScore(ScoreProxy proxy);

    public abstract void handleNiveau(NiveauProxy proxy);

    public abstract void handleMechant(MechantProxy proxy);

    public abstract void handleJoueur(JoueurProxy proxy);

    public abstract void handleCaseElement(CaseElementProxy proxy);

    public abstract void handleBonus(BonusProxy proxy);

    public T process(Class<?> clazz) {
        setResult(defaultValue);
        ApplicationEntityTypesProcessor.process(this, clazz);
        return result;
    }

    public T process(Object proxy) {
        setResult(defaultValue);
        ApplicationEntityTypesProcessor.process(this, proxy);
        return result;
    }

    protected void setResult(T result) {
        this.result = result;
    }
}
