// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.laby.client.managed.request;

import org.laby.shared.gae.MakesGaeRequests;
import org.laby.shared.scaffold.ScaffoldRequestFactory;

public interface ApplicationRequestFactory extends ScaffoldRequestFactory, MakesGaeRequests {

    ScoreRequest scoreRequest();

    NiveauRequest niveauRequest();

    MechantRequest mechantRequest();

    JoueurRequest joueurRequest();

    CaseElementRequest caseElementRequest();

    BonusRequest bonusRequest();
}
