// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.laby.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("org.laby.model.Bonus")
@ServiceName("org.laby.model.Bonus")
public interface BonusRequest extends RequestContext {

    abstract Request<java.lang.Long> countBonuses();

    abstract Request<java.util.List<org.laby.client.managed.request.BonusProxy>> findAllBonuses();

    abstract Request<java.util.List<org.laby.client.managed.request.BonusProxy>> findBonusEntries(int firstResult, int maxResults);

    abstract Request<org.laby.client.managed.request.BonusProxy> findBonus(Long id);

    abstract InstanceRequest<org.laby.client.managed.request.BonusProxy, java.lang.Void> remove();

    abstract InstanceRequest<org.laby.client.managed.request.BonusProxy, java.lang.Void> persist();
}
