// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.laby.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("org.laby.model.CaseElement")
@ServiceName("org.laby.model.CaseElement")
public interface CaseElementRequest extends RequestContext {

    abstract Request<java.lang.Long> countCaseElements();

    abstract Request<java.util.List<org.laby.client.managed.request.CaseElementProxy>> findAllCaseElements();

    abstract Request<java.util.List<org.laby.client.managed.request.CaseElementProxy>> findCaseElementEntries(int firstResult, int maxResults);

    abstract Request<org.laby.client.managed.request.CaseElementProxy> findCaseElement(Long id);

    abstract InstanceRequest<org.laby.client.managed.request.CaseElementProxy, java.lang.Void> remove();

    abstract InstanceRequest<org.laby.client.managed.request.CaseElementProxy, java.lang.Void> persist();
}
