// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.laby.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("org.laby.model.Joueur")
@ServiceName("org.laby.model.Joueur")
public interface JoueurRequest extends RequestContext {

    abstract Request<java.lang.Long> countJoueurs();

    abstract Request<java.util.List<org.laby.client.managed.request.JoueurProxy>> findAllJoueurs();

    abstract Request<java.util.List<org.laby.client.managed.request.JoueurProxy>> findJoueurEntries(int firstResult, int maxResults);

    abstract Request<org.laby.client.managed.request.JoueurProxy> findJoueur(Long id);

    abstract InstanceRequest<org.laby.client.managed.request.JoueurProxy, java.lang.Void> remove();

    abstract InstanceRequest<org.laby.client.managed.request.JoueurProxy, java.lang.Void> persist();
}
