// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.laby.client.managed.request;

import com.google.gwt.requestfactory.shared.EntityProxy;
import com.google.gwt.requestfactory.shared.ProxyForName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("org.laby.model.Joueur")
@ProxyForName("org.laby.model.Joueur")
public interface JoueurProxy extends EntityProxy {

    abstract Long getId();

    abstract Integer getVersion();

    abstract Integer getPosX();

    abstract Integer getPosY();

    abstract NiveauProxy getNiveau();

    abstract void setId(Long id);

    abstract void setVersion(Integer version);

    abstract void setPosX(Integer posX);

    abstract void setPosY(Integer posY);

    abstract void setNiveau(NiveauProxy niveau);
}
