// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.laby.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("org.laby.model.Mechant")
@ServiceName("org.laby.model.Mechant")
public interface MechantRequest extends RequestContext {

    abstract Request<java.lang.Long> countMechants();

    abstract Request<java.util.List<org.laby.client.managed.request.MechantProxy>> findAllMechants();

    abstract Request<java.util.List<org.laby.client.managed.request.MechantProxy>> findMechantEntries(int firstResult, int maxResults);

    abstract Request<org.laby.client.managed.request.MechantProxy> findMechant(Long id);

    abstract InstanceRequest<org.laby.client.managed.request.MechantProxy, java.lang.Void> remove();

    abstract InstanceRequest<org.laby.client.managed.request.MechantProxy, java.lang.Void> persist();
}
