// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.laby.client.managed.request;

import com.google.gwt.requestfactory.shared.EntityProxy;
import com.google.gwt.requestfactory.shared.ProxyForName;
import java.util.List;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("org.laby.model.Niveau")
@ProxyForName("org.laby.model.Niveau")
public interface NiveauProxy extends EntityProxy {

    abstract List<org.laby.client.managed.request.BonusProxy> getBonus();

    abstract List<org.laby.client.managed.request.MechantProxy> getVilains();

    abstract List<org.laby.client.managed.request.CaseElementProxy> getCases();

    abstract JoueurProxy getJoueur();

    abstract Long getId();

    abstract Integer getVersion();

    abstract String getNom();

    abstract String getCanvaCouloir();

    abstract String getCanvaMur();

    abstract String getCanvaBonus();

    abstract String getCanvaSortie();

    abstract String getCanvaMechants();

    abstract Integer getTailleX();

    abstract Integer getTailleY();

    abstract void setBonus(List<BonusProxy> bonus);

    abstract void setVilains(List<MechantProxy> vilains);

    abstract void setCases(List<CaseElementProxy> cases);

    abstract void setJoueur(JoueurProxy joueur);

    abstract void setId(Long id);

    abstract void setVersion(Integer version);

    abstract void setNom(String nom);

    abstract void setCanvaCouloir(String canvaCouloir);

    abstract void setCanvaMur(String canvaMur);

    abstract void setCanvaBonus(String canvaBonus);

    abstract void setCanvaSortie(String canvaSortie);

    abstract void setCanvaMechants(String canvaMechants);

    abstract void setTailleX(Integer tailleX);

    abstract void setTailleY(Integer tailleY);
}
