// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.laby.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("org.laby.model.Niveau")
@ServiceName("org.laby.model.Niveau")
public interface NiveauRequest extends RequestContext {

    abstract Request<java.lang.Long> countNiveaus();

    abstract Request<java.util.List<org.laby.client.managed.request.NiveauProxy>> findAllNiveaus();

    abstract Request<java.util.List<org.laby.client.managed.request.NiveauProxy>> findNiveauEntries(int firstResult, int maxResults);

    abstract Request<org.laby.client.managed.request.NiveauProxy> findNiveau(Long id);

    abstract InstanceRequest<org.laby.client.managed.request.NiveauProxy, java.lang.Void> remove();

    abstract InstanceRequest<org.laby.client.managed.request.NiveauProxy, java.lang.Void> persist();
}
