// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.laby.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("org.laby.model.Score")
@ServiceName("org.laby.model.Score")
public interface ScoreRequest extends RequestContext {

    abstract Request<java.lang.Long> countScores();

    abstract Request<java.util.List<org.laby.client.managed.request.ScoreProxy>> findAllScores();

    abstract Request<java.util.List<org.laby.client.managed.request.ScoreProxy>> findScoreEntries(int firstResult, int maxResults);

    abstract Request<org.laby.client.managed.request.ScoreProxy> findScore(Long id);

    abstract InstanceRequest<org.laby.client.managed.request.ScoreProxy, java.lang.Void> remove();

    abstract InstanceRequest<org.laby.client.managed.request.ScoreProxy, java.lang.Void> persist();
}
