// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.laby.client.managed.request;

import com.google.gwt.requestfactory.shared.EntityProxy;
import com.google.gwt.requestfactory.shared.ProxyForName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("org.laby.model.Score")
@ProxyForName("org.laby.model.Score")
public interface ScoreProxy extends EntityProxy {

    abstract Long getId();

    abstract Integer getVersion();

    abstract Long getScore();

    abstract String getUserName();

    abstract NiveauProxy getNiveau();

    abstract void setId(Long id);

    abstract void setVersion(Integer version);

    abstract void setScore(Long score);

    abstract void setUserName(String userName);

    abstract void setNiveau(NiveauProxy niveau);
}
