// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.laby.model;

import java.util.List;
import java.util.Random;
import org.laby.model.Niveau;
import org.springframework.stereotype.Component;

privileged aspect NiveauDataOnDemand_Roo_DataOnDemand {
    
    declare @type: NiveauDataOnDemand: @Component;
    
    private Random NiveauDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Niveau> NiveauDataOnDemand.data;
    
    public Niveau NiveauDataOnDemand.getNewTransientNiveau(int index) {
        org.laby.model.Niveau obj = new org.laby.model.Niveau();
        obj.setJoueur(null);
        obj.setNom("nom_" + index);
        obj.setCanvaCouloir("CanvaCouloir_" + index);
        obj.setCanvaMur("CanvaMur_" + index);
        obj.setCanvaBonus("CanvaBonus_" + index);
        obj.setCanvaSortie("CanvaSortie_" + index);
        obj.setCanvaMechants("CanvaMechants_" + index);
        obj.setTailleX(new Integer(index));
        obj.setTailleY(new Integer(index));
        return obj;
    }
    
    public Niveau NiveauDataOnDemand.getSpecificNiveau(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Niveau obj = data.get(index);
        return Niveau.findNiveau(obj.getId());
    }
    
    public Niveau NiveauDataOnDemand.getRandomNiveau() {
        init();
        Niveau obj = data.get(rnd.nextInt(data.size()));
        return Niveau.findNiveau(obj.getId());
    }
    
    public boolean NiveauDataOnDemand.modifyNiveau(Niveau obj) {
        return false;
    }
    
    public void NiveauDataOnDemand.init() {
        data = org.laby.model.Niveau.findNiveauEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Niveau' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.laby.model.Niveau>();
        for (int i = 0; i < 10; i++) {
            org.laby.model.Niveau obj = getNewTransientNiveau(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
