// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.laby.model;

import com.google.appengine.tools.development.testing.LocalServiceTestHelper;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.laby.model.NiveauDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

privileged aspect NiveauIntegrationTest_Roo_IntegrationTest {
    
    declare @type: NiveauIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: NiveauIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: NiveauIntegrationTest: @Transactional;
    
    @Autowired
    private NiveauDataOnDemand NiveauIntegrationTest.dod;
    
    private static final LocalServiceTestHelper NiveauIntegrationTest.helper = new LocalServiceTestHelper(new com.google.appengine.tools.development.testing.LocalDatastoreServiceTestConfig());
    
    @BeforeClass
    public static void NiveauIntegrationTest.setUp() {
        helper.setUp();
    }
    
    @AfterClass
    public static void NiveauIntegrationTest.tearDown() {
        helper.tearDown();
    }
    
    @Test
    public void NiveauIntegrationTest.testCountNiveaus() {
        org.junit.Assert.assertNotNull("Data on demand for 'Niveau' failed to initialize correctly", dod.getRandomNiveau());
        long count = org.laby.model.Niveau.countNiveaus();
        org.junit.Assert.assertTrue("Counter for 'Niveau' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void NiveauIntegrationTest.testFindNiveau() {
        org.laby.model.Niveau obj = dod.getRandomNiveau();
        org.junit.Assert.assertNotNull("Data on demand for 'Niveau' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Niveau' failed to provide an identifier", id);
        obj = org.laby.model.Niveau.findNiveau(id);
        org.junit.Assert.assertNotNull("Find method for 'Niveau' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Niveau' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void NiveauIntegrationTest.testFindAllNiveaus() {
        org.junit.Assert.assertNotNull("Data on demand for 'Niveau' failed to initialize correctly", dod.getRandomNiveau());
        long count = org.laby.model.Niveau.countNiveaus();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Niveau', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.laby.model.Niveau> result = org.laby.model.Niveau.findAllNiveaus();
        org.junit.Assert.assertNotNull("Find all method for 'Niveau' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Niveau' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void NiveauIntegrationTest.testFindNiveauEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Niveau' failed to initialize correctly", dod.getRandomNiveau());
        long count = org.laby.model.Niveau.countNiveaus();
        if (count > 20) count = 20;
        java.util.List<org.laby.model.Niveau> result = org.laby.model.Niveau.findNiveauEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Niveau' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Niveau' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void NiveauIntegrationTest.testFlush() {
        org.laby.model.Niveau obj = dod.getRandomNiveau();
        org.junit.Assert.assertNotNull("Data on demand for 'Niveau' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Niveau' failed to provide an identifier", id);
        obj = org.laby.model.Niveau.findNiveau(id);
        org.junit.Assert.assertNotNull("Find method for 'Niveau' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyNiveau(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Niveau' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NiveauIntegrationTest.testMerge() {
        org.laby.model.Niveau obj = dod.getRandomNiveau();
        org.junit.Assert.assertNotNull("Data on demand for 'Niveau' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Niveau' failed to provide an identifier", id);
        obj = org.laby.model.Niveau.findNiveau(id);
        boolean modified =  dod.modifyNiveau(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.laby.model.Niveau merged = (org.laby.model.Niveau) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Niveau' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NiveauIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Niveau' failed to initialize correctly", dod.getRandomNiveau());
        org.laby.model.Niveau obj = dod.getNewTransientNiveau(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Niveau' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Niveau' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Niveau' identifier to no longer be null", obj.getId());
    }
    
    @Test
    @Transactional(propagation = Propagation.SUPPORTS)
    public void NiveauIntegrationTest.testRemove() {
        org.laby.model.Niveau obj = dod.getRandomNiveau();
        org.junit.Assert.assertNotNull("Data on demand for 'Niveau' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Niveau' failed to provide an identifier", id);
        obj = org.laby.model.Niveau.findNiveau(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Niveau' with identifier '" + id + "'", org.laby.model.Niveau.findNiveau(id));
    }
    
}
