// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.laby.client.managed.activity;

import org.laby.client.managed.request.ApplicationEntityTypesProcessor;
import org.laby.client.managed.request.ApplicationRequestFactory;
import org.laby.client.managed.request.NiveauProxy;
import org.laby.client.managed.request.ScoreProxy;
import org.laby.client.managed.ui.NiveauListView;
import org.laby.client.managed.ui.NiveauMobileListView;
import org.laby.client.managed.ui.ScoreListView;
import org.laby.client.managed.ui.ScoreMobileListView;
import org.laby.client.scaffold.ScaffoldApp;
import org.laby.client.scaffold.place.ProxyListPlace;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.activity.shared.ActivityMapper;
import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;

public abstract class ApplicationMasterActivities_Roo_Gwt implements ActivityMapper {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    public Activity getActivity(Place place) {
        if (!(place instanceof ProxyListPlace)) {
            return null;
        }
        ProxyListPlace listPlace = (ProxyListPlace) place;
        return new ApplicationEntityTypesProcessor<Activity>() {

            @Override
            public void handleScore(ScoreProxy isNull) {
                setResult(new ScoreListActivity(requests, ScaffoldApp.isMobile() ? ScoreMobileListView.instance() : ScoreListView.instance(), placeController));
            }

            @Override
            public void handleNiveau(NiveauProxy isNull) {
                setResult(new NiveauListActivity(requests, ScaffoldApp.isMobile() ? NiveauMobileListView.instance() : NiveauListView.instance(), placeController));
            }

           
        }.process(listPlace.getProxyClass());
    }
}
