// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.laby.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.activity.shared.ActivityMapper;
import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.inject.Inject;
import org.laby.client.managed.request.ApplicationEntityTypesProcessor;
import org.laby.client.managed.request.ApplicationRequestFactory;
import org.laby.client.managed.request.BonusProxy;
import org.laby.client.managed.request.CaseElementProxy;
import org.laby.client.managed.request.JoueurProxy;
import org.laby.client.managed.request.MechantProxy;
import org.laby.client.managed.request.NiveauProxy;
import org.laby.client.managed.request.ScoreProxy;
import org.laby.client.managed.ui.BonusListView;
import org.laby.client.managed.ui.BonusMobileListView;
import org.laby.client.managed.ui.CaseElementListView;
import org.laby.client.managed.ui.CaseElementMobileListView;
import org.laby.client.managed.ui.JoueurListView;
import org.laby.client.managed.ui.JoueurMobileListView;
import org.laby.client.managed.ui.MechantListView;
import org.laby.client.managed.ui.MechantMobileListView;
import org.laby.client.managed.ui.NiveauListView;
import org.laby.client.managed.ui.NiveauMobileListView;
import org.laby.client.managed.ui.ScoreListView;
import org.laby.client.managed.ui.ScoreMobileListView;
import org.laby.client.scaffold.ScaffoldApp;
import org.laby.client.scaffold.place.ProxyListPlace;

public final class ApplicationMasterActivities extends ApplicationMasterActivities_Roo_Gwt {

    @Inject
    public ApplicationMasterActivities(ApplicationRequestFactory requests, PlaceController placeController) {
        this.requests = requests;
        this.placeController = placeController;
    }
}
