// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.laby.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.gwt.requestfactory.shared.EntityProxyId;
import com.google.gwt.requestfactory.shared.RequestContext;
import org.laby.client.managed.request.ApplicationRequestFactory;
import org.laby.client.managed.request.JoueurProxy;
import org.laby.client.managed.request.JoueurRequest;
import org.laby.client.managed.request.NiveauProxy;
import org.laby.client.managed.ui.JoueurDetailsView;
import org.laby.client.managed.ui.JoueurEditView;
import org.laby.client.managed.ui.JoueurListView;
import org.laby.client.managed.ui.JoueurMobileDetailsView;
import org.laby.client.managed.ui.JoueurMobileEditView;
import org.laby.client.scaffold.ScaffoldApp;
import org.laby.client.scaffold.place.CreateAndEditProxy;
import org.laby.client.scaffold.place.FindAndEditProxy;
import org.laby.client.scaffold.place.ProxyPlace;

public class JoueurActivitiesMapper {

    private final ApplicationRequestFactory requests;

    private final PlaceController placeController;

    public JoueurActivitiesMapper(ApplicationRequestFactory requests, PlaceController placeController) {
        this.requests = requests;
        this.placeController = placeController;
    }

    public Activity getActivity(ProxyPlace place) {
        switch(place.getOperation()) {
            case DETAILS:
                return new JoueurDetailsActivity((EntityProxyId<JoueurProxy>) place.getProxyId(), requests, placeController, ScaffoldApp.isMobile() ? JoueurMobileDetailsView.instance() : JoueurDetailsView.instance());
            case EDIT:
                return makeEditActivity(place);
            case CREATE:
                return makeCreateActivity();
        }
        throw new IllegalArgumentException("Unknown operation " + place.getOperation());
    }

    @SuppressWarnings("unchecked")
    private EntityProxyId<org.laby.client.managed.request.JoueurProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<JoueurProxy>) place.getProxyId();
    }

    private Activity makeCreateActivity() {
        JoueurEditView.instance().setCreating(true);
        final JoueurRequest request = requests.joueurRequest();
        Activity activity = new CreateAndEditProxy<JoueurProxy>(JoueurProxy.class, request, ScaffoldApp.isMobile() ? JoueurMobileEditView.instance() : JoueurEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(JoueurProxy proxy) {
                request.persist().using(proxy);
                return request;
            }
        };
        return new JoueurEditActivityWrapper(requests, ScaffoldApp.isMobile() ? JoueurMobileEditView.instance() : JoueurEditView.instance(), activity, null);
    }

    private Activity makeEditActivity(ProxyPlace place) {
        JoueurEditView.instance().setCreating(false);
        EntityProxyId<JoueurProxy> proxyId = coerceId(place);
        Activity activity = new FindAndEditProxy<JoueurProxy>(proxyId, requests, ScaffoldApp.isMobile() ? JoueurMobileEditView.instance() : JoueurEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(JoueurProxy proxy) {
                JoueurRequest request = requests.joueurRequest();
                request.persist().using(proxy);
                return request;
            }
        };
        return new JoueurEditActivityWrapper(requests, ScaffoldApp.isMobile() ? JoueurMobileEditView.instance() : JoueurEditView.instance(), activity, proxyId);
    }
}
