// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.laby.client.managed.activity;

import org.laby.client.managed.request.ApplicationRequestFactory;
import org.laby.client.managed.request.JoueurProxy;
import org.laby.client.scaffold.ScaffoldMobileApp;
import org.laby.client.scaffold.activity.IsScaffoldMobileActivity;
import org.laby.client.scaffold.place.AbstractProxyListActivity;
import org.laby.client.scaffold.place.ProxyListView;

import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.gwt.requestfactory.shared.Receiver;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.view.client.Range;

public class JoueurListActivity extends AbstractProxyListActivity<JoueurProxy> implements IsScaffoldMobileActivity {

    private final ApplicationRequestFactory requests;

    public JoueurListActivity(ApplicationRequestFactory requests, ProxyListView<org.laby.client.managed.request.JoueurProxy> view, PlaceController placeController) {
        super(placeController, view, JoueurProxy.class);
        this.requests = requests;
    }

    public Place getBackButtonPlace() {
        return ScaffoldMobileApp.ROOT_PLACE;
    }

    public String getBackButtonText() {
        return "Entities";
    }

    public Place getEditButtonPlace() {
        return null;
    }

    public String getTitleText() {
        return "Joueurs";
    }

    public boolean hasEditButton() {
        return false;
    }

    protected Request<java.util.List<org.laby.client.managed.request.JoueurProxy>> createRangeRequest(Range range) {
        return requests.joueurRequest().findJoueurEntries(range.getStart(), range.getLength());
    }

    protected void fireCountRequest(Receiver<Long> callback) {
        requests.joueurRequest().countJoueurs().fire(callback);
    }
}
