// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.laby.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.place.shared.Place;
import com.google.gwt.requestfactory.shared.EntityProxyId;
import com.google.gwt.requestfactory.shared.Receiver;
import com.google.gwt.user.client.ui.AcceptsOneWidget;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import org.laby.client.managed.activity.NiveauEditActivityWrapper.View;
import org.laby.client.managed.request.ApplicationRequestFactory;
import org.laby.client.managed.request.BonusProxy;
import org.laby.client.managed.request.CaseElementProxy;
import org.laby.client.managed.request.JoueurProxy;
import org.laby.client.managed.request.MechantProxy;
import org.laby.client.managed.request.NiveauProxy;
import org.laby.client.managed.ui.BonusListEditor;
import org.laby.client.managed.ui.CaseElementListEditor;
import org.laby.client.managed.ui.MechantListEditor;
import org.laby.client.scaffold.activity.IsScaffoldMobileActivity;
import org.laby.client.scaffold.place.ProxyEditView;
import org.laby.client.scaffold.place.ProxyListPlace;
import org.laby.client.scaffold.place.ProxyPlace;

public abstract class NiveauEditActivityWrapper_Roo_Gwt implements Activity, IsScaffoldMobileActivity {

    protected Activity wrapped;

    protected View<?> view;

    protected ApplicationRequestFactory requests;

    @Override
    public void start(AcceptsOneWidget display, EventBus eventBus) {
        view.setBonusPickerValues(Collections.<BonusProxy>emptyList());
        requests.bonusRequest().findBonusEntries(0, 50).with(org.laby.client.managed.ui.BonusProxyRenderer.instance().getPaths()).fire(new Receiver<List<BonusProxy>>() {

            public void onSuccess(List<BonusProxy> response) {
                List<BonusProxy> values = new ArrayList<BonusProxy>();
                values.add(null);
                values.addAll(response);
                view.setBonusPickerValues(values);
            }
        });
        view.setVilainsPickerValues(Collections.<MechantProxy>emptyList());
        requests.mechantRequest().findMechantEntries(0, 50).with(org.laby.client.managed.ui.MechantProxyRenderer.instance().getPaths()).fire(new Receiver<List<MechantProxy>>() {

            public void onSuccess(List<MechantProxy> response) {
                List<MechantProxy> values = new ArrayList<MechantProxy>();
                values.add(null);
                values.addAll(response);
                view.setVilainsPickerValues(values);
            }
        });
        view.setCasesPickerValues(Collections.<CaseElementProxy>emptyList());
        requests.caseElementRequest().findCaseElementEntries(0, 50).with(org.laby.client.managed.ui.CaseElementProxyRenderer.instance().getPaths()).fire(new Receiver<List<CaseElementProxy>>() {

            public void onSuccess(List<CaseElementProxy> response) {
                List<CaseElementProxy> values = new ArrayList<CaseElementProxy>();
                values.add(null);
                values.addAll(response);
                view.setCasesPickerValues(values);
            }
        });
        view.setJoueurPickerValues(Collections.<JoueurProxy>emptyList());
        requests.joueurRequest().findJoueurEntries(0, 50).with(org.laby.client.managed.ui.JoueurProxyRenderer.instance().getPaths()).fire(new Receiver<List<JoueurProxy>>() {

            public void onSuccess(List<JoueurProxy> response) {
                List<JoueurProxy> values = new ArrayList<JoueurProxy>();
                values.add(null);
                values.addAll(response);
                view.setJoueurPickerValues(values);
            }
        });
        wrapped.start(display, eventBus);
    }

    public interface View_Roo_Gwt<V extends org.laby.client.scaffold.place.ProxyEditView<org.laby.client.managed.request.NiveauProxy, V>> extends ProxyEditView<NiveauProxy, V> {

        void setBonusPickerValues(Collection<BonusProxy> values);

        void setVilainsPickerValues(Collection<MechantProxy> values);

        void setCasesPickerValues(Collection<CaseElementProxy> values);

        void setJoueurPickerValues(Collection<JoueurProxy> values);
    }
}
