// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.laby.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.gwt.requestfactory.shared.EntityProxyId;
import com.google.gwt.requestfactory.shared.RequestContext;
import org.laby.client.managed.request.ApplicationRequestFactory;
import org.laby.client.managed.request.NiveauProxy;
import org.laby.client.managed.request.ScoreProxy;
import org.laby.client.managed.request.ScoreRequest;
import org.laby.client.managed.ui.ScoreDetailsView;
import org.laby.client.managed.ui.ScoreEditView;
import org.laby.client.managed.ui.ScoreListView;
import org.laby.client.managed.ui.ScoreMobileDetailsView;
import org.laby.client.managed.ui.ScoreMobileEditView;
import org.laby.client.scaffold.ScaffoldApp;
import org.laby.client.scaffold.place.CreateAndEditProxy;
import org.laby.client.scaffold.place.FindAndEditProxy;
import org.laby.client.scaffold.place.ProxyPlace;

public class ScoreActivitiesMapper {

    private final ApplicationRequestFactory requests;

    private final PlaceController placeController;

    public ScoreActivitiesMapper(ApplicationRequestFactory requests, PlaceController placeController) {
        this.requests = requests;
        this.placeController = placeController;
    }

    public Activity getActivity(ProxyPlace place) {
        switch(place.getOperation()) {
            case DETAILS:
                return new ScoreDetailsActivity((EntityProxyId<ScoreProxy>) place.getProxyId(), requests, placeController, ScaffoldApp.isMobile() ? ScoreMobileDetailsView.instance() : ScoreDetailsView.instance());
            case EDIT:
                return makeEditActivity(place);
            case CREATE:
                return makeCreateActivity();
        }
        throw new IllegalArgumentException("Unknown operation " + place.getOperation());
    }

    @SuppressWarnings("unchecked")
    private EntityProxyId<org.laby.client.managed.request.ScoreProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<ScoreProxy>) place.getProxyId();
    }

    private Activity makeCreateActivity() {
        ScoreEditView.instance().setCreating(true);
        final ScoreRequest request = requests.scoreRequest();
        Activity activity = new CreateAndEditProxy<ScoreProxy>(ScoreProxy.class, request, ScaffoldApp.isMobile() ? ScoreMobileEditView.instance() : ScoreEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(ScoreProxy proxy) {
                request.persist().using(proxy);
                return request;
            }
        };
        return new ScoreEditActivityWrapper(requests, ScaffoldApp.isMobile() ? ScoreMobileEditView.instance() : ScoreEditView.instance(), activity, null);
    }

    private Activity makeEditActivity(ProxyPlace place) {
        ScoreEditView.instance().setCreating(false);
        EntityProxyId<ScoreProxy> proxyId = coerceId(place);
        Activity activity = new FindAndEditProxy<ScoreProxy>(proxyId, requests, ScaffoldApp.isMobile() ? ScoreMobileEditView.instance() : ScoreEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(ScoreProxy proxy) {
                ScoreRequest request = requests.scoreRequest();
                request.persist().using(proxy);
                return request;
            }
        };
        return new ScoreEditActivityWrapper(requests, ScaffoldApp.isMobile() ? ScoreMobileEditView.instance() : ScoreEditView.instance(), activity, proxyId);
    }
}
