// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.laby.client.scaffold.laby.ui;

import org.laby.client.managed.request.ApplicationRequestFactory;
import org.laby.client.managed.request.NiveauProxy;
import org.laby.client.scaffold.laby.Laby;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.FocusPanel;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import com.google.gwt.widgetideas.graphics.client.GWTCanvas;

public class LabyView  extends Composite  {

	/**
	 * Implemented by the owner of the view.
	 */
	public interface Delegate {

		void editClicked();

	}
	
	
    private static final Binder BINDER = GWT.create(Binder.class);

    private static LabyView instance;

    NiveauProxy proxy;

    @UiField
    SpanElement displayRenderer;

    @UiField 
    FocusPanel gamePanel;
    
    GWTCanvas canvas ;
    
    
    
    @UiField
    HasClickHandlers edit;

    @UiField
    HasClickHandlers delete;

    private Delegate delegate;

    public LabyView() {
        initWidget(BINDER.createAndBindUi(this));
     
    }

    public static LabyView instance() {
        if (instance == null) {
            instance = new LabyView();
        }
        return instance;
    }

    public Widget asWidget() {
        return this;
    }

    public boolean confirm(String msg) {
        return Window.confirm(msg);
    }

    public NiveauProxy getValue() {
        return proxy;
    }


    @UiHandler("edit")
    public void onEditClicked(ClickEvent e) {
        delegate.editClicked();
    }

    public void setDelegate(Delegate delegate) {
        this.delegate = delegate;
    }

    interface Binder extends UiBinder<HTMLPanel, LabyView> {
    }
        

    public void setValue(NiveauProxy niveau,ApplicationRequestFactory requestFactory) {
        this.proxy = niveau;

        gamePanel.clear();
        canvas = new GWTCanvas(400,400);
        gamePanel.add(canvas);
        
		 
		 Laby laby = new Laby(requestFactory,canvas,niveau);
	      
		
		 laby.drawGame();
		 gamePanel.addKeyPressHandler(laby);
		 gamePanel.addClickHandler(laby);
		  
		
       
        displayRenderer.setInnerText(org.laby.client.managed.ui.NiveauProxyRenderer.instance().render(proxy));
    }
    

}
