// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.laby.client.managed.ui;

import com.google.gwt.requestfactory.ui.client.ProxyRenderer;
import org.laby.client.managed.request.CaseElementProxy;
import org.laby.client.managed.request.NiveauProxy;

public class CaseElementProxyRenderer extends ProxyRenderer<CaseElementProxy> {

    private static org.laby.client.managed.ui.CaseElementProxyRenderer INSTANCE;

    protected CaseElementProxyRenderer() {
        super(new String[] { "id" });
    }

    public static org.laby.client.managed.ui.CaseElementProxyRenderer instance() {
        if (INSTANCE == null) {
            INSTANCE = new CaseElementProxyRenderer();
        }
        return INSTANCE;
    }

    public String render(CaseElementProxy object) {
        if (object == null) {
            return "";
        }
        return object.getId() + " (" + object.getId() + ")";
    }
}
