// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.laby.client.managed.ui;

import com.google.gwt.requestfactory.ui.client.ProxyRenderer;
import org.laby.client.managed.request.JoueurProxy;
import org.laby.client.managed.request.NiveauProxy;

public class JoueurProxyRenderer extends ProxyRenderer<JoueurProxy> {

    private static org.laby.client.managed.ui.JoueurProxyRenderer INSTANCE;

    protected JoueurProxyRenderer() {
        super(new String[] { "id" });
    }

    public static org.laby.client.managed.ui.JoueurProxyRenderer instance() {
        if (INSTANCE == null) {
            INSTANCE = new JoueurProxyRenderer();
        }
        return INSTANCE;
    }

    public String render(JoueurProxy object) {
        if (object == null) {
            return "";
        }
        return object.getId() + " (" + object.getId() + ")";
    }
}
