// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.laby.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.user.cellview.client.CellTable;
import com.google.gwt.user.cellview.client.HasKeyboardSelectionPolicy.KeyboardSelectionPolicy;
import com.google.gwt.user.cellview.client.TextColumn;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.HTMLPanel;
import java.util.HashSet;
import java.util.Set;
import org.laby.client.managed.request.MechantProxy;
import org.laby.client.managed.request.NiveauProxy;
import org.laby.client.scaffold.place.AbstractProxyListView;

public abstract class MechantListView_Roo_Gwt extends AbstractProxyListView<MechantProxy> {

    @UiField
    CellTable<MechantProxy> table;

    protected Set<String> paths = new HashSet<String>();

    public void init() {
        paths.add("id");
        table.addColumn(new TextColumn<MechantProxy>() {

            Renderer<java.lang.Long> renderer = new AbstractRenderer<java.lang.Long>() {

                public String render(java.lang.Long obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(MechantProxy object) {
                return renderer.render(object.getId());
            }
        }, "Id");
        paths.add("version");
        table.addColumn(new TextColumn<MechantProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(MechantProxy object) {
                return renderer.render(object.getVersion());
            }
        }, "Version");
        paths.add("posX");
        table.addColumn(new TextColumn<MechantProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(MechantProxy object) {
                return renderer.render(object.getPosX());
            }
        }, "Pos X");
        paths.add("posY");
        table.addColumn(new TextColumn<MechantProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(MechantProxy object) {
                return renderer.render(object.getPosY());
            }
        }, "Pos Y");
        paths.add("imageX");
        table.addColumn(new TextColumn<MechantProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(MechantProxy object) {
                return renderer.render(object.getImageX());
            }
        }, "Image X");
        paths.add("imageY");
        table.addColumn(new TextColumn<MechantProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(MechantProxy object) {
                return renderer.render(object.getImageY());
            }
        }, "Image Y");
        paths.add("type");
        table.addColumn(new TextColumn<MechantProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(MechantProxy object) {
                return renderer.render(object.getType());
            }
        }, "Type");
        paths.add("niveau");
        table.addColumn(new TextColumn<MechantProxy>() {

            Renderer<org.laby.client.managed.request.NiveauProxy> renderer = org.laby.client.managed.ui.NiveauProxyRenderer.instance();

            @Override
            public String getValue(MechantProxy object) {
                return renderer.render(object.getNiveau());
            }
        }, "Niveau");
    }
}
