// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.laby.client.managed.ui;

import com.google.gwt.requestfactory.ui.client.ProxyRenderer;
import org.laby.client.managed.request.MechantProxy;
import org.laby.client.managed.request.NiveauProxy;

public class MechantProxyRenderer extends ProxyRenderer<MechantProxy> {

    private static org.laby.client.managed.ui.MechantProxyRenderer INSTANCE;

    protected MechantProxyRenderer() {
        super(new String[] { "id" });
    }

    public static org.laby.client.managed.ui.MechantProxyRenderer instance() {
        if (INSTANCE == null) {
            INSTANCE = new MechantProxyRenderer();
        }
        return INSTANCE;
    }

    public String render(MechantProxy object) {
        if (object == null) {
            return "";
        }
        return object.getId() + " (" + object.getId() + ")";
    }
}
