// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.laby.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.user.cellview.client.CellTable;
import com.google.gwt.user.cellview.client.HasKeyboardSelectionPolicy.KeyboardSelectionPolicy;
import com.google.gwt.user.cellview.client.TextColumn;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.HTMLPanel;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.laby.client.managed.request.BonusProxy;
import org.laby.client.managed.request.CaseElementProxy;
import org.laby.client.managed.request.JoueurProxy;
import org.laby.client.managed.request.MechantProxy;
import org.laby.client.managed.request.NiveauProxy;
import org.laby.client.scaffold.place.AbstractProxyListView;

public abstract class NiveauListView_Roo_Gwt extends AbstractProxyListView<NiveauProxy> {

    @UiField
    CellTable<NiveauProxy> table;

    protected Set<String> paths = new HashSet<String>();

    public void init() {
//        paths.add("bonus");
//        table.addColumn(new TextColumn<NiveauProxy>() {
//
//            Renderer<java.util.List> renderer = org.laby.client.scaffold.place.CollectionRenderer.of(org.laby.client.managed.ui.BonusProxyRenderer.instance());
//
//            @Override
//            public String getValue(NiveauProxy object) {
//                return renderer.render(object.getBonus());
//            }
//        }, "Bonus");
//        paths.add("vilains");
//        table.addColumn(new TextColumn<NiveauProxy>() {
//
//            Renderer<java.util.List> renderer = org.laby.client.scaffold.place.CollectionRenderer.of(org.laby.client.managed.ui.MechantProxyRenderer.instance());
//
//            @Override
//            public String getValue(NiveauProxy object) {
//                return renderer.render(object.getVilains());
//            }
//        }, "Vilains");
//        paths.add("cases");
//        table.addColumn(new TextColumn<NiveauProxy>() {
//
//            Renderer<java.util.List> renderer = org.laby.client.scaffold.place.CollectionRenderer.of(org.laby.client.managed.ui.CaseElementProxyRenderer.instance());
//
//            @Override
//            public String getValue(NiveauProxy object) {
//                return renderer.render(object.getCases());
//            }
//        }, "Cases");
//        paths.add("joueur");
//        table.addColumn(new TextColumn<NiveauProxy>() {
//
//            Renderer<org.laby.client.managed.request.JoueurProxy> renderer = org.laby.client.managed.ui.JoueurProxyRenderer.instance();
//
//            @Override
//            public String getValue(NiveauProxy object) {
//                return renderer.render(object.getJoueur());
//            }
//        }, "Joueur");
        paths.add("id");
        table.addColumn(new TextColumn<NiveauProxy>() {

            Renderer<java.lang.Long> renderer = new AbstractRenderer<java.lang.Long>() {

                public String render(java.lang.Long obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(NiveauProxy object) {
                return renderer.render(object.getId());
            }
        }, "Id");
//        paths.add("version");
//        table.addColumn(new TextColumn<NiveauProxy>() {
//
//            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {
//
//                public String render(java.lang.Integer obj) {
//                    return obj == null ? "" : String.valueOf(obj);
//                }
//            };
//
//            @Override
//            public String getValue(NiveauProxy object) {
//                return renderer.render(object.getVersion());
//            }
//        }, "Version");
        paths.add("nom");
        table.addColumn(new TextColumn<NiveauProxy>() {

            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {

                public String render(java.lang.String obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(NiveauProxy object) {
                return renderer.render(object.getNom());
            }
        }, "Nom");
//        paths.add("canvaCouloir");
//        table.addColumn(new TextColumn<NiveauProxy>() {
//
//            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {
//
//                public String render(java.lang.String obj) {
//                    return obj == null ? "" : String.valueOf(obj);
//                }
//            };
//
//            @Override
//            public String getValue(NiveauProxy object) {
//                return renderer.render(object.getCanvaCouloir());
//            }
//        }, "Canva Couloir");
//        paths.add("canvaMur");
//        table.addColumn(new TextColumn<NiveauProxy>() {
//
//            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {
//
//                public String render(java.lang.String obj) {
//                    return obj == null ? "" : String.valueOf(obj);
//                }
//            };
//
//            @Override
//            public String getValue(NiveauProxy object) {
//                return renderer.render(object.getCanvaMur());
//            }
//        }, "Canva Mur");
//        paths.add("canvaBonus");
//        table.addColumn(new TextColumn<NiveauProxy>() {
//
//            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {
//
//                public String render(java.lang.String obj) {
//                    return obj == null ? "" : String.valueOf(obj);
//                }
//            };
//
//            @Override
//            public String getValue(NiveauProxy object) {
//                return renderer.render(object.getCanvaBonus());
//            }
//        }, "Canva Bonus");
//        paths.add("canvaSortie");
//        table.addColumn(new TextColumn<NiveauProxy>() {
//
//            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {
//
//                public String render(java.lang.String obj) {
//                    return obj == null ? "" : String.valueOf(obj);
//                }
//            };
//
//            @Override
//            public String getValue(NiveauProxy object) {
//                return renderer.render(object.getCanvaSortie());
//            }
//        }, "Canva Sortie");
//        paths.add("canvaMechants");
//        table.addColumn(new TextColumn<NiveauProxy>() {
//
//            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {
//
//                public String render(java.lang.String obj) {
//                    return obj == null ? "" : String.valueOf(obj);
//                }
//            };
//
//            @Override
//            public String getValue(NiveauProxy object) {
//                return renderer.render(object.getCanvaMechants());
//            }
//        }, "Canva Mechants");
//        paths.add("tailleX");
//        table.addColumn(new TextColumn<NiveauProxy>() {
//
//            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {
//
//                public String render(java.lang.Integer obj) {
//                    return obj == null ? "" : String.valueOf(obj);
//                }
//            };
//
//            @Override
//            public String getValue(NiveauProxy object) {
//                return renderer.render(object.getTailleX());
//            }
//        }, "Taille X");
//        paths.add("tailleY");
//        table.addColumn(new TextColumn<NiveauProxy>() {
//
//            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {
//
//                public String render(java.lang.Integer obj) {
//                    return obj == null ? "" : String.valueOf(obj);
//                }
//            };
//
//            @Override
//            public String getValue(NiveauProxy object) {
//                return renderer.render(object.getTailleY());
//            }
//        }, "Taille Y");
    }
}
