// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.laby.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import java.util.List;
import org.laby.client.managed.request.BonusProxy;
import org.laby.client.managed.request.CaseElementProxy;
import org.laby.client.managed.request.JoueurProxy;
import org.laby.client.managed.request.MechantProxy;
import org.laby.client.managed.request.NiveauProxy;
import org.laby.client.scaffold.place.ProxyDetailsView;
import org.laby.client.scaffold.place.ProxyListView;

public abstract class NiveauDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<NiveauProxy> {

    @UiField
    SpanElement bonus;

    @UiField
    SpanElement vilains;

    @UiField
    SpanElement cases;

    @UiField
    SpanElement joueur;

    @UiField
    SpanElement id;

    @UiField
    SpanElement version;

    @UiField
    SpanElement nom;

    @UiField
    SpanElement canvaCouloir;

    @UiField
    SpanElement canvaMur;

    @UiField
    SpanElement canvaBonus;

    @UiField
    SpanElement canvaSortie;

    @UiField
    SpanElement canvaMechants;

    @UiField
    SpanElement tailleX;

    @UiField
    SpanElement tailleY;

    NiveauProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(NiveauProxy proxy) {
        this.proxy = proxy;
       id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        nom.setInnerText(proxy.getNom() == null ? "" : String.valueOf(proxy.getNom()));
        canvaCouloir.setInnerText(proxy.getCanvaCouloir() == null ? "" : String.valueOf(proxy.getCanvaCouloir()));
        canvaMur.setInnerText(proxy.getCanvaMur() == null ? "" : String.valueOf(proxy.getCanvaMur()));
        canvaBonus.setInnerText(proxy.getCanvaBonus() == null ? "" : String.valueOf(proxy.getCanvaBonus()));
        canvaSortie.setInnerText(proxy.getCanvaSortie() == null ? "" : String.valueOf(proxy.getCanvaSortie()));
        canvaMechants.setInnerText(proxy.getCanvaMechants() == null ? "" : String.valueOf(proxy.getCanvaMechants()));
        tailleX.setInnerText(proxy.getTailleX() == null ? "" : String.valueOf(proxy.getTailleX()));
        tailleY.setInnerText(proxy.getTailleY() == null ? "" : String.valueOf(proxy.getTailleY()));
        displayRenderer.setInnerText(org.laby.client.managed.ui.NiveauProxyRenderer.instance().render(proxy));
    }
}
