// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.laby.client.managed.ui;

import com.google.gwt.requestfactory.ui.client.ProxyRenderer;
import org.laby.client.managed.request.NiveauProxy;
import org.laby.client.managed.request.ScoreProxy;

public class ScoreProxyRenderer extends ProxyRenderer<ScoreProxy> {

    private static org.laby.client.managed.ui.ScoreProxyRenderer INSTANCE;

    protected ScoreProxyRenderer() {
        super(new String[] { "id" });
    }

    public static org.laby.client.managed.ui.ScoreProxyRenderer instance() {
        if (INSTANCE == null) {
            INSTANCE = new ScoreProxyRenderer();
        }
        return INSTANCE;
    }

    public String render(ScoreProxy object) {
        if (object == null) {
            return "";
        }
        return object.getId() + " (" + object.getId() + ")";
    }
}
